Repository CMU-313/fall23-nodebb-michaels-angels, pull requests merged in 2023-10, with the labels that each got.

#18 Added endorsement button for admin when the respond to posts
  themes/nodebb-theme-persona/less/bootstrap/buttons.less
  themes/nodebb-theme-persona/templates/partials/topic/post.tpl
Labels: bug, enhancement

#20 Added beginner functionality for a question and answer feature on posts and topics
  .gitignore
  node_modules/nodebb-plugin-composer-default/static/templates/composer.tpl
  node_modules/nodebb-plugin-question-and-answer/.eslintrc
  node_modules/nodebb-plugin-question-and-answer/.gitattributes
  node_modules/nodebb-plugin-question-and-answer/library.js
  node_modules/nodebb-plugin-question-and-answer/package.json
  node_modules/nodebb-plugin-question-and-answer/plugin.json
  node_modules/nodebb-plugin-question-and-answer/static/languages/de/qanda.json
  node_modules/nodebb-plugin-question-and-answer/static/languages/en-GB/qanda.json
  node_modules/nodebb-plugin-question-and-answer/static/languages/en-US/qanda.json
  node_modules/nodebb-plugin-question-and-answer/static/languages/fa-IR/qanda.json
  node_modules/nodebb-plugin-question-and-answer/static/languages/fr/qanda.json
  node_modules/nodebb-plugin-question-and-answer/static/languages/he/qanda.json
  node_modules/nodebb-plugin-question-and-answer/static/languages/pt-PT/qanda.json
  node_modules/nodebb-plugin-question-and-answer/static/languages/ru/qanda.json
  node_modules/nodebb-plugin-question-and-answer/static/languages/tr/qanda.json
  node_modules/nodebb-plugin-question-and-answer/static/languages/zh-CN/qanda.json
  node_modules/nodebb-plugin-question-and-answer/static/lib/.eslintrc
  node_modules/nodebb-plugin-question-and-answer/static/lib/admin.js
  node_modules/nodebb-plugin-question-and-answer/static/lib/main.js
  node_modules/nodebb-plugin-question-and-answer/static/style.scss
  pidfile 2
  pidfile 3
  pidfile 4
  pidfile 5
  pidfile 6
  pidfile 7
Labels: bug, enhancement, help wanted

#22 Implemented functionality within each topic
  node_modules/nodebb-plugin-question-and-answer/library.js
Labels: enhancement

#25 Added front-end functionality to question/answer function
  node_modules/nodebb-plugin-question-and-answer/static/templates/admin/plugins/question-and-answer-items.tpl
  node_modules/nodebb-plugin-question-and-answer/static/templates/admin/plugins/question-and-answer.tpl
  node_modules/nodebb-plugin-question-and-answer/static/templates/partials/question-and-answer/topic-jsonld.tpl
Labels: enhancement

#28 Added tests and db schema change for be right back status
  public/openapi/components/schemas/Chats.yaml
  public/openapi/components/schemas/UserObject.yaml
  src/socket.io/modules.js
  test/messaging.js
Labels: testing
